version: '3.7'
networks:
  default:
    name: redis
    external: false
services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - default
    ports:
      - "6379:6379"