version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  search-api:
    image: search-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-api
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./app.env
        target: /app/app.env
    depends_on:
      - redis